cache:
  container_name: cache
  image: redis
api:
  container_name: api
  build: ./images/api/
  volumes:
    - ./api/:/api/
  working_dir: /api/
  command: npm start
  ports:
    - "8000:3000"
  links:
    - database
    - cache
ui:
  container_name: ui
  volumes:
    - ./ui/:/ui/
  build: ./images/ui/
  command: /ui-runtime/node_modules/polymer-cli/bin/polymer.js serve --port 5000 --hostname 0.0.0.0 --npm  --component-dir node_modules
  working_dir: /ui/
  ports:
    - "5000:5000"
nginx:
  container_name: nginx
  image: nginx
  volumes:
    - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
  links:
    - ui
    - api
database:
  container_name: db
  build: ./images/db/
  ports:
    - "27000:27017"